potion-duration: 10 # in minutes
region-name: km_safe_from_radiation
# Set this to false when you want to create safe region by yourself
use-radius: true
#Radius from spawnpoint, where safe region should be
radius: 250
world-names:
- world
