# Indicates version of this file, please don't touch!
file-protocol-version-dont-touch: 0

# Boss bar shown on the screen when player has lugol's iodine effect.
lugols-iodine-bar:
  # Colorable title shown on the bar.
  title: 'Lugol''s Iodine Effect'
  # Color of the bar, possible values:
  # blue, green, pink, purple, red, white, yellow
  color: green
  # Style of the bar, possible values:
  # segmented_6, segmented_10, segmented_12, segmented_20, solid
  style: segmented_20
  # Additional effects given for the player, possible values:
  # create_fog, darken_sky, play_boss_music
  flags: []

# Lugol's iodine potion item options.
lugols-iodine-potion:
  # Name of the item.
  name: 'Lugol''s Iodine'
  # Description of the item.
  description: 'Radiation resistance ({0})'
  # Duration in seconds of effect given when a player consumes the potion.
  duration: 600
  # Colorable broadcast message shown when a player consumes the potion.
  drink-message: '{0}&c drank {1}.'

# Radiation zone options.
radiation:
  # Boss bar shown on the screen when a player is in the zone.
  bar:
    # Colorable title shown on the bar.
    title: 'Radiation Zone'
    # Color of the bar, possible values:
    # blue, green, pink, purple, red, white, yellow
    color: red
    # Style of the bar, possible values:
    # segmented_6, segmented_10, segmented_12, segmented_20, solid
    style: solid
    # Additional effects given for the player, possible values:
    # create_fog, darken_sky, play_boss_music
    flags: [darken_sky]
  # Effects given in the radiation zone.
  effects:
    # Name of the effect. List of effect names is available here:
    # https://minecraft.gamepedia.com/Status_effect#Effect_IDs
    wither:
      # Level of the effect, eg. level 5 gives Wither V effect.
      level: 5
      # Should this effect produce more, translucent, particles?
      ambient: false
      # Does this effect produce particles?
      has-particles: false
      # Does this effect give an icon?
      has-icon: false
    hunger:
      # Level of the effect, eg. level 5 gives Wither V effect.
      level: 1
      # Should this effect produce more, translucent, particles?
      ambient: false
      # Does this effect produce particles?
      has-particles: false
      # Does this effect give an icon?
      has-icon: false
  # Colorable broadcast message shown when a player enters radiation zone.
  escape-message: '{0}&c has escaped to radiation zone.'

# Usataw wartosc na true, jezeli chcesz, aby strefa wolna od radiacji byla tworzona automatycznie od punktu spawnu
use-radius: true
# Promien, w którym od punktu spawnu powinna obowiązywać strefa wolna od radiacji
radius: 250
