potion-duration: 10 # in minutes
region-name: km_safe_from_radiation
use-radius: true # Usataw wartosc na true, jezeli chcesz, aby strefa wolna od radiacji byla tworzona automatycznie od punktu spawnu
radius: 250 # Promien, w którym od punktu spawnu powinna obowiązywać strefa wolna od radiacji
world-names:
- world
